apiVersion: apiextensions.k8s.io/v1  # Specifies the Kubernetes API version for CRDs
kind: CustomResourceDefinition  # Defines a CRD resource
metadata:
  name: mycustomresources.example.com  # Name of the CRD
spec:
  group: example.com  # API group name
  names:
    kind: MyCustomResource  # Kind of the custom resource
    listKind: MyCustomResourceList  # List kind
    plural: mycustomresources  # Plural name for the resource
    singular: mycustomresource  # Singular name
  scope: Namespaced  # Can be "Namespaced" or "Cluster"
  versions:
    - name: v1  # Version of the CRD
      served: true  # Whether this version is served
      storage: true  # Whether this version is the storage version
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer