apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dpm
  labels:
    app: nginx
spec:             # specification for the deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:             # specification for the pods
      containers:
        - name: nginx
          image: nginx:1.16
          ports:
            - containerPort: 80

